version: '3'
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./website/build/:/usr/share/nginx/html/website

  nginx:
    image: '${NGINX_IMAGE}'
    ports:
      - "80:80"
    volumes:
      - website:/usr/share/nginx/html/website

volumes:
  website:
